### ISSUE TITLE
Unguarded use of JSON.parse in node client

### ISSUE THREAD

**Issue by camelpunch** [kaltura/clients-generator#358]
Hi there!

We're on the older, crustier, client: https://www.npmjs.com/package/kaltura. However, we believe this bug might exist in the modern client, too: https://www.npmjs.com/package/kaltura-client.

We're getting runtime errors when the Kaltura server returns HTML instead of JSON. The `JSON.parse` calls in e.g. [KalturaClientBase](https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/d92a98014ff73c1e2631e7d5517b59ce238427c7/KalturaClientBase.js#L314) cause exceptions like (note that these are coming from the old client):

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/backend/node_modules/kaltura/KalturaClientBase.js:394:20)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19
```

We are planning to patch our systems with try/catches - just a heads-up in case you're unaware!

**Comment by kaltura-hooks** [comment]
Hi @camelpunch,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by tan-tan-kanarek** [comment]
Such error may occur in case of server crash such as error 500.
If you can specify the request that caused it we may find the error on the server side.

**Comment by camelpunch** [comment]
OK - we'll retrieve the server's response.

We think that the client should also be able to handle non-JSON without crashing. As users of the client we have no ability to catch such errors ourselves. If the network is faulty, we'd prefer not to have our application crash if possible.

**Comment by tan-tan-kanarek** [comment]
Regarding the client, I agree.
As for the server issue, we need the request to solve it, the response probably won't give us much info beside its http error code.

**Comment by camelpunch** [comment]
Understood - we'll get both. Thanks!

**Comment by tan-tan-kanarek** [comment]
It helps, thanks.
Partner-id will help as well.

**Comment by camelpunch** [comment]
1776261

**Comment by camelpunch** [comment]
Just checking in - has there been any progress on the investigation?

**Comment by tan-tan-kanarek** [comment]
Sorry, not yet.

**Comment by jessp01** [comment]
I believe this can be closed but if that's not the case, feel free to reopen and add recent examples.
Thanks,
