### ISSUE TITLE
Feature request - action execution callbacks

### ISSUE THREAD

**Issue by yusitnikov** [kaltura/clients-generator#425]
Hi there!

I'd like to contribute an enhancement to php client libraries - add callback arguments to service action methods that will be executed only when the response comes from the server (also in the case of the multi-request). It will allow to write a code that is agnostic to the multi-request mode (works the same way inside and outside of a multi-request).

*Before starting to work on the pull request, I wonder if there are some concerns about adding this functionality.*

Technical details:
- add `$onSuccess` and `$onError` optional arguments to service action methods that support multi-requests (so, for instance, `function update($entryId, \Kaltura\Client\Type\BaseEntry $baseEntry)` will become `function update($entryId, \Kaltura\Client\Type\BaseEntry $baseEntry, $onSuccess = null, $onError = null)`)
- these new arguments will receive callbacks that will be executed by the client library when the response comes from the server:
  - when executing a single API request, the callback will be called immediately after the request execution
  - when adding an API request to a multi-request queue, the callback will be executed only after performing the multi-request and will receive the result of the relevant multi-request item as an argument
- when callbacks are not specified or empty, the client library will work exactly as it did before

So, that way, service action method will become a kind of a promise, and the code will be written in the following way:
```php
$someService->someAction(
    $anArgument, $anotherArgument,
    function(ActionResponseType $response) {
        doSomethingWithResponse($response);
    }
)
```
and this code will behave exactly the same way when executing it inside or outside of a multi-request.

Thanks,
Yura.

**Comment by tan-tan-kanarek** [comment]
Hey Yura,
Thank you for your idea, generally this is a very good practice that we indeed implement if few async coding languages such as Javascript, Java and C#, usually by using request builders that returned from the action method, then you can build the request and execute it after loading callbacks on the builder.
However, since PHP considered as synchronous coding language with no real threading support, we thought that it would be much more simple just to return the parsed response.
Note that if you choose to implement callbacks, they probably should be implemented as first argument as many of the arguments today are optional and adding callback as last argument will force you to check the type of each argument to know if it's an optional argument or a callback, though in PHP the callback might be a simple string which may cause more confusion.

**Comment by yusitnikov** [comment]
Hi @tan-tan-kanarek ,

> since PHP considered as synchronous coding language with no real threading support

No, I didn't mean anything about threading support :) Just put the callback into the queue when calling the action method in a multi-request (it could be stored on the ServiceActionCall object) and execute it later when the multi-request response is here.

> we thought that it would be much more simple just to return the parsed response

Well, in 95% of cases it's trivial and comfortable to do so. But sometimes, in large complicated systems (did I mention before that I'm a MediaSpace developer? :) ), one piece of the code may call startMultiRequest() and doMultiRequest(), and another piece of the code (that is located in a different method and even different file, because of the code separation between models) may call the service actions inside of it. With the current architecture, it would be much harder for the "caller" to do something with the final response.

> Note that if you choose to implement callbacks, they probably should be implemented as first argument as many of the arguments today are optional and adding callback as last argument will force you to check the type of each argument to know if it's an optional argument or a callback, though in PHP the callback might be a simple string which may cause more confusion.

Sorry, but I didn't understand what you mean. The callback arguments will be optional, so they could be safely added to the end.
Also, adding a new argument to the beginning would break compatibility with the previous client library versions.

**Comment by kaltura-hooks** [comment]
Hi @yusitnikov,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,
