### ISSUE TITLE
'KalturaClient' object has no attribute 'elasticsearch'

### ISSUE THREAD

**Issue by mhamilt** [kaltura/clients-generator#447]
# Issue

Running the [eSearch example](https://developer.kaltura.com/console/service/eSearch/action/searchEntry?query=ese) from the API Console in Python 3.7.3 (and any Python 3 env) I get the error

```python
'KalturaClient' object has no attribute 'elasticsearch'
```

form the line

```python
client.elasticsearch.eSearch.searchEntry(search_params, pager)
```

## Example Code

Below is the example code, running without issue, from the API Console

```python
from KalturaClient import *
from KalturaClient.Plugins.Core import *
from KalturaClient.Plugins.ElasticSearch import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "YOUR_KALTURA_SECRET",
      "YOUR_USER_ID",
      KalturaSessionType.ADMIN,
      YOUR_PARTNER_ID)
client.setKs(ks)

search_params = KalturaESearchEntryParams()
search_params.searchOperator = KalturaESearchEntryOperator()
search_params.searchOperator.searchItems = []
search_params.searchOperator.searchItems[0] = KalturaESearchEntryItem()
search_params.searchOperator.searchItems[0].fieldName = KalturaESearchEntryFieldName.NAME
search_params.searchOperator.searchItems[0].itemType = KalturaESearchItemType.PARTIAL
search_params.searchOperator.searchItems[0].searchTerm = "SEARCH TERM"
pager = KalturaPager()

result = client.elasticsearch.eSearch.searchEntry(search_params, pager)
print(result)
```

---

**NB:**

This section from the API docs 
```python
search_params.searchOperator.searchItems = []
search_params.searchOperator.searchItems[0] = KalturaESearchEntryItem()
```

also fails with:

```python
    search_params.searchOperator.searchItems[0] = KalturaESearchEntryItem()
IndexError: list assignment index out of range
```

Though the solution is trivial, it is maybe worth clearing this up.

**Comment by kaltura-hooks** [comment]
Hi @mhamilt,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by mhamilt** [comment]
### Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?

This issue appears to be python specific. The same example code run with the Javascript and NodeJs APIs appear to run without issue. I have not tried the other individual APIs


### Which Kaltura deployment you're using ...

I am interfacing with what I believe is Kaltura SaaS.  

Since this appears to be a python specific error, I believe it is something a problem in the autogenerated python interface. That is, unless the install of the **KalturaGeneratedAPIClientsPython** modules goes beyond a simple

```bash
pip install KalturaApiClient
```

**Comment by jessp01** [comment]
Hello @mhamilt,

Thank you very much for your report. We will fix the generator accordingly. Here's a working example:
```python
from KalturaClient import *
from KalturaClient.Plugins.Core import *
from KalturaClient.Plugins.ElasticSearch import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "YOUR_KALTURA_SECRET",
      "YOUR_USER_ID",
      KalturaSessionType.ADMIN,
      YOUR_PARTNER_ID)
client.setKs(ks)

search_params = KalturaESearchEntryParams()
search_params.searchOperator = KalturaESearchEntryOperator()
search_params.searchOperator.searchItems = []
search_params.searchOperator.searchItems.append(KalturaESearchEntryItem())
search_params.searchOperator.searchItems[0].fieldName = KalturaESearchEntryFieldName.NAME
search_params.searchOperator.searchItems[0].itemType = KalturaESearchItemType.PARTIAL
search_params.searchOperator.searchItems[0].searchTerm = "james"
pager = KalturaPager()

result = client.elasticSearch.eSearch.searchEntry(search_params, pager)
print result
```

Cheers,

**Comment by mhamilt** [comment]
Ah, just a typo. Apologies, I should have spotted it in the first place.

**Comment by jessp01** [comment]
No apology necessary; we aim for the generator to produce ready to use code out of the box so your report is much appreciated:)

**Comment by jessp01** [comment]
Hi @mhamilt,

I just deployed a fix to the generator and the Python code generated for this action (https://developer.kaltura.com/console/service/eSearch/action/searchEntry) is now correct. 

Thanks again,
