### ISSUE TITLE
NameError: name 'KalturaBulkUploadXmlJobData' is not defined

### ISSUE THREAD

**Issue by tvmvmaor** [kaltura/clients-generator#510]
I'm getting an error when I'm trying to upload an xml to Kaltura Saas via API. See code below.

Note: If I use KalturaBulkUploadJobData() instead of KalturaBulkUploadXmlJobData() the xml-file is imported (I can see it in the KMS), but it interprets it as a csv, so that obviously doesn't work. The code example from https://developer.kaltura.com/api-docs/service/media/action/bulkUploadAdd

If I upload the xml-file manually via KMS or via https://developer.kaltura.com/api-docs/service/media/action/bulkUploadAdd it works fine.

Python versions: 3.5.9, 3.7.6, 3.8.1 (also tested on Python 2)
OS: Debian 9, Debian 8, MacOS (have tested on several different servers)
Client API version: KalturaApiClient-15.14.0

**test.py:**
```
from KalturaClient import *
from KalturaClient.Plugins.Core import *

config = KalturaConfiguration([removed])
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "[removed]",
      "[removed]",
      KalturaSessionType.ADMIN,
     [removed])
client.setKs(ks)

file_name = "tvmidtvest-d472d2f9-a004-4ae1-8795-1885674a63d7.xml"

file_data = open(file_name, 'rb')

bulk_upload_data = KalturaBulkUploadXmlJobData()
bulk_upload_entry_data = KalturaBulkUploadEntryData()

result = client.media.bulkUploadAdd(file_data)

print(result)
```
**Error:** 
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    bulk_upload_data = KalturaBulkUploadXmlJobData()
NameError: name 'KalturaBulkUploadXmlJobData' is not defined
```

**Comment by kaltura-hooks** [comment]
Hi @tvmvmaor,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @tvmvmaor,

There's a minor bug in the code generator which we will address.
Please use the following:

```python
from KalturaClient import *
from KalturaClient.Plugins.Core import *
from KalturaClient.Plugins.BulkUploadXml import *

config = KalturaConfiguration()
config.serviceUrl = "https://www.kaltura.com/"
client = KalturaClient(config)
ks = client.session.start(
      "ADMIN_SECRET",
      "YOUR_USER_ID",
      KalturaSessionType.ADMIN,
      PARTNER_ID)
client.setKs(ks)

file_data = open('/path/to/bulk.xml', 'rb')
bulk_upload_data = KalturaBulkUploadXmlJobData()
bulk_upload_entry_data = KalturaBulkUploadEntryData()

result = client.media.bulkUploadAdd(file_data,bulk_upload_data,bulk_upload_entry_data)
print(result)
```

Cheers and thanks for reporting,

**Comment by tvmvmaor** [comment]
It works! Thank you very much 👍

**Comment by jessp01** [comment]
You're welcome, @tvmvmaor .
