### ISSUE TITLE
Exception when adding streams to KalturaMediaEntry

### ISSUE THREAD

**Issue by ehamdy-inmobly** [kaltura/clients-generator#535]
Using python==3.6
KalturaClientApi==15.20

I want to define audio tracks to the uploaded video by adding streams in  KalturaMediaEntry.streams, but i got 
exception: 'dict' object has no attribute 'toParams' in addObjectIfDefined function in KalturaClient/Base.py at line 113
Here is the used snipt:
    
media_entry = KalturaMediaEntry()
media_entry.mediaType = KalturaMediaType.VIDEO
media_entry.name = video.name
media_entry.description = video.description
media_entry.categories = ",".join(map(str, video.categories))
media_entry.tags = ",".join(map(str, video.tags))
media_entry.accessControlId = video.access_control_id
media_entry.streams = [{"type": "audio", "trackIndex": 1, "language": "kor"}]
result = sesion.media.addFromUrl(media_entry, video.url)

Although we are using this code to upload single video to Kaltura without any problems (without defining the streams property).

**Comment by kaltura-hooks** [comment]
Hi @ehamdy-inmobly,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @ehamdy-inmobly ,

If you're looking to add multiple audio track to an entry, please see:
https://github.com/kaltura/server/issues/6795

For the ways to accomplish that.
