### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by andreyfedoseev** [kaltura/clients-generator#57]
KalturaClient for Python doesn't support Python3 at the moment. The typical problems are:

1. Relative imports: `from Core import *`. It can be replaced with `from .Core import *`
2. Calling `some_dict.has_key(key)` for dictionaries. This can be replaced with `key in some_dict`
3. `except AttributeError, e` syntax it `try/except` blocks. This can be replaced with `except AttributeError as e`
4. Using `map` to produce a list. `map` returns a generator object in Python3. If it's necessary to have a list, list comprehensions can be used instead: `[func(item) for item in iterable]`
5. Using `print` statement. This can be replaced with `print("foo")` (works in both Python 2 and 3)

**Comment by kaltura-hooks** [comment]
Hi @andreyfedoseev,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @andreyfedoseev,

Thank you for raising the issue. We are aware of it but have no immediate plans to address it. 
That said, being FOSS, we are certainly happy to accept contributions in the form of pull requests.
The client libraries are auto generated from this repo:
https://github.com/kaltura/clients-generator/
You can make a pull request here:
https://github.com/kaltura/clients-generator/tree/Lynx-12.8.0/sources/python

The unittests should also be revised accordingly here:
https://github.com/kaltura/clients-generator/tree/Lynx-12.8.0/tests/ovp/python/KalturaClient/tests

To generate the client post making these changes, one needs a Kaltura Server ENV, if you don't already have one, see howtos for installing it here:
https://github.com/kaltura/platform-install-packages/#documentation-and-guides

Then, to generate a new python client, one should run:
php /opt/kaltura/app/generator/generate.php python

And the resulting client will then be placed here:
/opt/kaltura/web/content/clientlibs/python

Would love to get your contribution and am happy to assist should you have additional questions in regards to the process,

**Comment by ccorbacho** [comment]
@andreyfedoseev Those are relatively minor. The bigger problem is that the poster library is not Python 3 compatible (which these bindings use to handle multi-part uploads) - this needs to be ripped out and replaced with something like requests which does and is 2 & 3 compatible.

@jessp01 I'm thinking about doing the work to support this (as we use Kaltura at work with Python 3, and are having to write custom wrappers of our own because of this). Is there any restriction on what the oldest version of Python is that we want to support here? I'd prefer to just have one code base that can support Python 2.7 & Python 3 (and not worry about 2.6 or earlier - although 2.6 could be done at a stretch)?

**Comment by jessp01** [comment]
Hi @ccorbacho,

First of all, thank you in advance for your future contribution.
I utterly agree about having one code base to support both the 2 and 3 branches, no use splitting into two separate clients, especially since hopefully, everyone would eventually adopt the 3 branch, though the adoption rate is painfully slow, which is rather understandable in light of the amount of breakage. I mean, the changes made in the 3 branch even break print statements in many code bits.

As for the minimum supported version, seeing how the two stable branches are 2.7.13 and 3.6.0, I don't think it's terrible to no longer support 2.6. That said, 2.6 is the official version supplied for RHEL/CentOS 6, which are still quite commonly used. Granted, upgrading from the SCL repo is not hard and RHEL/CentOS 6 is not the latest distro version [RHEL/CentOS 7 includes Python 2.7] but still, if the effort needed to support both 2.6 and 2.7 is not vast, I'd rather it was made.

**Comment by ccorbacho** [comment]
I've put up a PR for this here:

https://github.com/kaltura/clients-generator/pull/102

**Comment by jessp01** [comment]
https://github.com/kaltura/clients-generator/pull/102 was merged. Thanks, @ccorbacho.
