### ISSUE TITLE
Where to get KalturaClient.xml from?

### ISSUE THREAD

**Issue by jakob-stoeck** [kaltura/clients-generator#73]
Without this file the generation is not working. I haven’t found any documentation to where I might get it from.

**Comment by kaltura-hooks** [comment]
Hi @jakob-stoeck,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by jessp01** [comment]
Hello @jakob-stoeck,

If you're working against our SaaS, you can get the schema from here: http://www.kaltura.com/api_v3/api_schema.php
Alternatively, if you just want to use a pre-generated client [which is what you should do unless you want to make changes to the client], you can obtain them from here:
https://developer.kaltura.com/api-docs/#/Client%20Libraries

And there are also repos that hold the latest nightly version [as well as older ones] here:
https://github.com/kaltura?utf8=%E2%9C%93&q=generated&type=&language=

When working with a self host ENV [CE or OnPrem], the file can be found here:
/opt/kaltura/web/content/clientlibs/KalturaClient.xml

**Comment by jakob-stoeck** [comment]
Hi @jessp01, thank you for the quick response! Yes, I’d like to propose some changes to the Java client.

Adding your comment to the README of this repo would be really nice as it was not obvious for me.

**Comment by jessp01** [comment]
Hi @jakob-stoeck, you are right, it should be documented. We'll take care of that. Thank you in advance for your contribution:)

**Comment by jessp01** [comment]
README updated: https://github.com/kaltura/clients-generator/pull/77
Thanks, @jakob-stoeck.
